import "./globals.css";
import Header from "./header/page";
import Footer from "./footer/page";
import ReduxProvider from "./components/ReduxProvider";

export const metadata = {
  title: "GooMarket",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
